/**
 * milk-mcp auth setup
 *
 * Authenticates with Remember The Milk and saves credentials.
 */

import { createInterface } from "readline/promises";
import { mkdirSync, writeFileSync, existsSync, chmodSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { RtmClient } from "./rtm-client.js";

export async function runAuth(args: string[]): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  const prompt = (question: string): Promise<string> => rl.question(question);

  console.log("\n🥛 milk-mcp — RTM Authentication Setup\n");
  console.log("You'll need an API key and shared secret from RTM.");
  console.log("Get them at: https://www.rememberthemilk.com/services/api/keys.rtm\n");

  // Accept from args or env or prompt
  let apiKey = args[0] ?? process.env.RTM_API_KEY ?? "";
  let sharedSecret = args[1] ?? process.env.RTM_SHARED_SECRET ?? "";

  if (!apiKey) {
    apiKey = await prompt("Enter your RTM API Key: ");
  } else {
    console.log(`Using API key from ${args[0] ? "CLI arg" : "env"}: ${apiKey.slice(0, 8)}...`);
  }

  if (!sharedSecret) {
    sharedSecret = await prompt("Enter your RTM Shared Secret: ");
  } else {
    console.log(`Using shared secret from ${args[1] ? "CLI arg" : "env"}.`);
  }

  apiKey = apiKey.trim();
  sharedSecret = sharedSecret.trim();

  if (!apiKey || !sharedSecret) {
    console.error("❌ API key and shared secret are required.");
    rl.close();
    process.exit(1);
  }

  // Step 1: Get a frob
  console.log("\n⏳ Getting authorization frob from RTM...");
  let frob: string;
  try {
    frob = await RtmClient.getFrob(apiKey, sharedSecret);
  } catch (err) {
    console.error(`❌ Failed to get frob: ${err}`);
    console.error("Check your API key and shared secret.");
    rl.close();
    process.exit(1);
  }

  // Step 2: Build the auth URL
  const authUrl = RtmClient.getAuthUrl(apiKey, sharedSecret, frob);
  console.log("\n✅ Got frob. Now you need to authorize milk-mcp in your browser.\n");
  console.log("👉 Open this URL:\n");
  console.log(`   ${authUrl}\n`);
  console.log('Log in to RTM and click "Allow Access". Then come back here.');

  await prompt("\nPress ENTER when you have authorized the app in your browser...");

  // Step 3: Exchange frob for auth token
  console.log("\n⏳ Exchanging frob for auth token...");
  let authToken: string;
  try {
    authToken = await RtmClient.getToken(apiKey, sharedSecret, frob);
  } catch (err) {
    console.error(`❌ Failed to get auth token: ${err}`);
    console.error("Make sure you clicked 'Allow Access' in the browser before pressing ENTER.");
    rl.close();
    process.exit(1);
  }

  console.log(`✅ Got auth token: ${authToken.slice(0, 12)}...`);

  // Step 4: Write config file
  const configDir = join(homedir(), ".config", "milk-mcp");
  const configPath = join(configDir, "config");

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  const configContent = [
    "# milk-mcp configuration",
    "# Generated by: npx milk-mcp auth",
    `# Generated: ${new Date().toISOString()}`,
    "#",
    "# Keep this file private — it grants full access to your RTM account.",
    "",
    `RTM_API_KEY=${apiKey}`,
    `RTM_SHARED_SECRET=${sharedSecret}`,
    `RTM_AUTH_TOKEN=${authToken}`,
    "",
  ].join("\n");

  writeFileSync(configPath, configContent, "utf-8");
  chmodSync(configPath, 0o600); // owner read/write only

  console.log(`\n✅ Config written to: ${configPath}`);
  console.log("   Permissions set to 600 (owner-only).\n");

  // Step 5: Verify
  console.log("⏳ Verifying connection to RTM...");
  try {
    const client = new RtmClient({ apiKey, sharedSecret, authToken });
    const lists = await client.getLists();
    console.log(`✅ Connected! Found ${lists.length} lists in your RTM account.\n`);
  } catch (err) {
    console.error(`⚠️  Config saved but verification failed: ${err}`);
    console.error("Your credentials may be wrong. Try running the auth setup again.");
    rl.close();
    process.exit(1);
  }

  console.log("🎉 All done! Add milk-mcp to your Claude Code config:\n");
  console.log("   claude mcp add milk-mcp -- npx milk-mcp");
  console.log("\n   Then in Claude Code, ask Claude to: rtm_setup_project MyProjectName\n");

  rl.close();
}
